paths:
  output_dir: "output"
  voice_dir: "input/voice"

subtitle:
  speakers:
    "アメノちゃん": "#9D0C0C" # 赤
    "ディアちゃん": "#004F6E" # 青
  font: "assets/font/MPLUSRounded1c-Medium.ttf"
  font_size: 40
  bg_color: "white"
  width: 1920
  height: 150
  padding_x: 250
  silent_duration: 0.25 # 音声後の無音期間(秒)

